name: Deploy to Production

on:
  push:
    branches:
      - master

env:  
  PRODUCTION_SERVER: ${{ vars.PRODUCTION_SERVER }}
  PRODUCTION_USER: ${{ vars.PRODUCTION_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: master don't think I need this anymore.
    steps:
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.NEW_PRODUCTION_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
      shell: bash

    - name: Add SSH Host
      run: |
        ssh-keyscan -H ${{ env.PRODUCTION_SERVER }} >> ~/.ssh/known_hosts
      shell: bash

    - name: checkout
      uses: actions/checkout@v3

    - name: Clone & Install
      run: |
        ssh ${{ env.PRODUCTION_USER }}@${{ env.PRODUCTION_SERVER }} "
        cd ~/production; \
        git pull; \ 
        source venv/bin/activate; \
        pip install --upgrade pip; \
        pip install -r requirements.txt"
      shell: bash



