name: Deploy to Production

on:
  push:
    branches:
      - master

env:
  PRODUCTION_SERVER: '${{ vars.PRODUCTION_SERVER }}'
  PRODUCTION_USER: '${{ vars.PRODUCTION_USER }}'

jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: master
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: echo "this is prod key '${{ secrets.PRODUCTION_USER }}'"

      shell: bash

  