name: Deploy to Production

on:
  push:
    branches:
      - master

env:
  PRODUCTION_SERVER: ${{ secrets.PRODUCTION_SERVER }}
  PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        echo "${{ secrets.PRODUCTION_SSH_KEY }}" > prod_key
        chmod 600 prod_key
        echo $PRODUCTION_USER
        ssh -o StrictHostKeyChecking=no -i prod_key $PRODUCTION_USER@$PRODUCTION_SERVER
      shell: bash

  