name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        echo "${{ secrets.PRODUCTION_SSH_KEY }}" > prod_key
        chmod 600 prod_key
        ssh -v -o StrictHostKeyChecking=no -i prod_key ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_SERVER }} "
          cd /home/repairshoprssh/repairshopr
          git pull origin main
          pip install --upgrade -r requirements.txt
        "
      env:
        PRODUCTION_SERVER: ${{ secrets.PRODUCTION_SERVER }}
        PRODUCTION_USER: ${{ secrets.PRODUCTION_USER }}
      shell: bash
