name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        echo "${{ secrets.PRODUCTION_SSH_KEY }}" > prod_key
        chmod 600 prod_key
        echo "${{ vars.PRODUCTION_USER }}"
        ssh -o StrictHostKeyChecking=no -i prod_key ${{ vars.PRODUCTION_USER }}@${{ vars.PRODUCTION_SERVER }}
      shell: bash

  