name: Deploy to Production

on:
  push:
    branches:
      - master

env:  
  PRODUCTION_SERVER: ${{ vars.PRODUCTION_SERVER }}
  PRODUCTION_USER: ${{ vars.PRODUCTION_USER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: master
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.NEW_PRODUCTION_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ls -la ~/.ssh
      shell: bash

    - name: Deploy to Production
      run: ssh -o StrictHostKeyChecking=no ${{ env.PRODUCTION_USER }}@${{ env.PRODUCTION_SERVER }} "whoami"
      shell: bash
