name: Deploy to Production

on:
  push:
    branches:
      - master

jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: master
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to Production  
      run: |
        echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh ${{ vars.PRODUCTION_USER }}@${{ vars.PRODUCTION_SERVER }} 
        whoami
      shell: bash

  